#apache:
#  rocketmq:
#    #消费者的配置
#    consumer:
#      pushConsumer: XiaourPushConsumer
#    #生产者的配置
#    producer:
#      producerGroup: Xiaour
#    #$Nameserver的地址,这里配置你MQ安装的机器上的IP就好，我这里在本机安装的
#    namesrvAddr: 172.18.3.71:9876;172.18.3.72:9876;172.18.3.73:9876